---
latitude: 41.91277
longitude: 12.43957
map_zoom: 12
name: Grand Hotel Tiberio
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: Via Lattanzio 51
  street2: ''
  state: ''
  city: Rome
  country: 
  zip_code: '00136'
_hotel_id: GRA762
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
